### ISSUE TITLE
[FEATURE] docker, docker compose and rclone support?

### ISSUE THREAD

**Issue by aniel300** [hendrikbgr/discord-cloud-storage#14]
any plans for supporting docker, docker compose and rclone?

**Comment by hendrikbgr** [comment]
yes I can add it soon

**Comment by aniel300** [comment]
ok I will wait patiently 🙏

**Comment by hendrikbgr** [comment]
Added in v1.0.4

**Comment by hendrikbgr** [comment]
https://github.com/hendrikbgr/discord-cloud-storage/releases/tag/v1.0.4

**Comment by aniel300** [comment]
are there any steps and directions on how to get it going on docker, docker compose and rclone?

**Comment by aniel300** [comment]
> https://github.com/hendrikbgr/discord-cloud-storage/releases/tag/v1.0.4

are there any steps and directions on how to get it going on docker, docker compose and rclone?

**Comment by aniel300** [comment]
@hendrikbgr did u added docker compose and rclone support?
