### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by Hass1000** [hendrikbgr/discord-cloud-storage#5]
**Describe the bug**

When trying to upload a file this error happens: `FileNotFoundError: [Errno 2] No such file or directory: 'temp_upload/1GB.bin'`

**To Reproduce**

Just selecting and uploading this file causes the error

**Expected behavior**

it should just upload

**Screenshots**

![image](https://github.com/hendrikbgr/discord-cloud-storage/assets/54211493/62b775e1-9716-4c84-8a6f-893753084e05)

**Desktop**

Windows server 2022

**Comment by hendrikbgr** [comment]
Hello, this is due to windows. I am currently working on a windows version and it can be expected to be release today or tomorrow. I still need to do some testing but you can find the current development status of the windows integration on the 'windows' branch.

**Comment by hendrikbgr** [comment]
https://github.com/hendrikbgr/discord-cloud-storage/tree/windows

**Comment by Hass1000** [comment]
> fixed now with v1.0.2 -> https://github.com/hendrikbgr/discord-cloud-storage/releases/tag/v1.0.2

Hi, I tried the new version and I am still getting the same error

**Comment by hendrikbgr** [comment]
should be fixed now in `main` https://github.com/hendrikbgr/discord-cloud-storage/commit/315ce65e884867d288affeb6005436551bd27885

**Comment by hendrikbgr** [comment]
if this still does not work create the following folders manually in the projects rood dir. `temp_upload` `temp_chunks` `temp_download`
